---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "admin1234"
mysql_db: "wordpress"
mysql_user: "ubuntu"
mysql_password: "user1234"

#HTTP Settings
http_host: "wordpresslemp"
http_conf: "wordpresslemp.conf"
http_port: "80"